// src/utils/constants.js

export const TEMPLATES = [
  { id: 'ieee',     label: 'IEEE',     desc: 'Conference format' },
  { id: 'acm',      label: 'ACM',      desc: 'Digital library' },
  { id: 'springer', label: 'Springer', desc: 'LNCS format' },
  { id: 'elsevier', label: 'Elsevier', desc: 'Journal format' },
  { id: 'apa',      label: 'APA',      desc: '7th edition' },
  { id: 'arxiv',    label: 'arXiv',    desc: 'Preprint' },
];

export const PIPELINE_STAGES = [
  { n: 1, name: 'Extract',   icon: '⬡', desc: 'PDF/DOCX → blocks + tables' },
  { n: 2, name: 'Parse',     icon: '◈', desc: 'Blocks → Document' },
  { n: 3, name: 'Canon',     icon: '◎', desc: 'Validate + repair + score' },
  { n: 4, name: 'Normalize', icon: '◇', desc: 'Unicode + math → LaTeX' },
  { n: 5, name: 'Render',    icon: '◉', desc: 'Document → .tex' },
  { n: 6, name: 'Compile',   icon: '▣', desc: '.tex → PDF' },
];

// Mock pipeline simulation for frontend dev (replace with real API calls)
export function simulatePipeline({ onStage, onLog, onDone }) {
  const now = () => new Date().toLocaleTimeString('en-GB', { hour12: false });

  const logEntries = [
    [0,    'info', '══════════════════════════════════════'],
    [50,   'info', `RUN START  ${now()}`],
    [100,  'info', '══════════════════════════════════════'],
    [300,  'info', '[1] Extractor — PDF/DOCX → text + tables'],
    [700,  'ok',   '  extracted: 24,812 chars | 3 tables | 2 images'],
    [900,  'debug','  OCR engine: pix2tex (subprocess mode)'],
    [1100, 'info', '[2] Parser — raw text → Document'],
    [1500, 'ok',   "  title='Deep Learning for Structured...' "],
    [1700, 'ok',   '  authors=4  sections=8  refs=42'],
    [2000, 'info', '[3] Canon — validate + repair + score'],
    [2400, 'ok',   '  confidence=0.87  renderable=True'],
    [2500, 'warn', '  ! 1 author with no affiliation (Li Wei)'],
    [2600, 'ok',   '  repairs=2  warnings=1'],
    [2800, 'info', '[4] Normalizer — unicode + math → LaTeX'],
    [3200, 'ok',   '  normalized: 3 Greek chars, 7 math symbols'],
    [3300, 'ok',   '  inline equations: 12 wrapped in $...$'],
    [3500, 'info', '[5] Renderer — Document → LaTeX [ieee]'],
    [3900, 'ok',   '  → intermediate/generated.tex (4.2 KB)'],
    [4100, 'info', '[6] Compiler — pdflatex pass 1/2 ...'],
    [4700, 'info', '         pdflatex pass 2/2 ...'],
    [5300, 'ok',   '  PDF written → output/paper_ieee.pdf'],
    [5400, 'ok',   '══════════════════════════════════════'],
    [5500, 'ok',   `RUN END  (4.7s)  ✓`],
  ];

  logEntries.forEach(([delay, type, msg]) => {
    setTimeout(() => onLog({ type, msg, ts: now() }), delay);
  });

  PIPELINE_STAGES.forEach((s, i) => {
    const base = i * 800 + 200;
    setTimeout(() => onStage(s.n, 'running'), base);
    setTimeout(() => onStage(s.n, 'done'),    base + 700);
  });

  setTimeout(() => onDone({
    sections:   8,
    refs:       42,
    tables:     3,
    confidence: 87,
    template:   'ieee',
    elapsed:    '4.7s',
    texPreview:
`% Generated by ai-paper-formatter
% Template: IEEEtran  |  Confidence: 87%

\\documentclass[conference]{IEEEtran}
\\usepackage{amsmath,amssymb,amsfonts}
\\usepackage{graphicx}
\\usepackage{hyperref}

\\begin{document}

\\title{Deep Learning for Structured Content
Extraction and IEEE-Compliant Reconstruction}

\\author{
  \\IEEEauthorblockN{Samaira Mittal}
  \\IEEEauthorblockA{\\textit{Dept. Computer Science}\\\\
    XYZ Institute, India\\\\
    s.mittal@xyz.edu}
  \\and
  \\IEEEauthorblockN{Arjun Mehta}
  \\IEEEauthorblockA{\\textit{Dept. Computer Science}\\\\
    XYZ Institute, India}
}

\\maketitle

\\begin{abstract}
We present a six-stage pipeline for automated
extraction and IEEE-compliant reformatting of
academic papers from PDF or DOCX sources...
\\end{abstract}

\\begin{IEEEkeywords}
document processing, LaTeX, NLP, OCR
\\end{IEEEkeywords}

\\section{Introduction}
Modern academic publishing demands strict
formatting compliance across IEEE, ACM,
Springer and other major venues...`,
  }), 5600);
}

export function formatFileSize(bytes) {
  if (!bytes) return '—';
  if (bytes < 1024)        return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
}
